## Pandas - Python and Numerical Data Analysis

In [7]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from pandas import Series, DataFrame

In [8]:
# Pandas has additional data structures (beyond array and arange)
# Series and DataFrame

s = pd.Series([4, 7, -5, 3])
's >', s, 's.values >', s.values, 's.index >', s.index

('s >',
 0    4
 1    7
 2   -5
 3    3
 dtype: int64,
 's.values >',
 array([ 4,  7, -5,  3], dtype=int64),
 's.index >',
 RangeIndex(start=0, stop=4, step=1))

In [9]:
s = Series([4, 7, -5, 3]) # without pd.
's >', s, 's.values >', s.values, 's.index >', s.index

('s >',
 0    4
 1    7
 2   -5
 3    3
 dtype: int64,
 's.values >',
 array([ 4,  7, -5,  3], dtype=int64),
 's.index >',
 RangeIndex(start=0, stop=4, step=1))

In [10]:
s2 = Series([4, 7, -5, 3], index=['d', 'b', 'a', 'c'])
's2 >', s2, 's2.values >', s2.values, 's2.index >', s2.index

('s2 >',
 d    4
 b    7
 a   -5
 c    3
 dtype: int64,
 's2.values >',
 array([ 4,  7, -5,  3], dtype=int64),
 's2.index >',
 Index(['d', 'b', 'a', 'c'], dtype='object'))

In [12]:
s2['a']

-5

In [13]:
# we can filter members
s2[s2>0]

d    4
b    7
c    3
dtype: int64

In [14]:
# obvious math
s2**3 # cubes

d     64
b    343
a   -125
c     27
dtype: int64

In [15]:
# check presence
print ('b' in s2) # check if 'b' is spresent in s2
print ('f' in s2) # check if 'f' is spresent in s2

True
False


In [17]:
# convert Python structures into Series
s_dict = {'Ohio':35000, 'Texas':71000, 'Oregon':16000, 'Utah':5000}
s3 = pd.Series(s_dict)
s3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [19]:
states = ['California', 'Ohio', 'Oregon', 'Texas','Utah']
s4 = Series(s_dict, index=states)
s4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Utah           5000.0
dtype: float64